name: GMusic
options:
  bundleIdPrefix: com.ivangrigin
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

targets:
  GMusic:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GMusic
    dependencies:
      - target: GMusicWidgets
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivangrigin.GMusic
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: GMusic/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: GMusic/App/GMusic.entitlements
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"

  GMusicWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GMusicWidgets
      - path: GMusic/Shared/Widgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivangrigin.GMusic.GMusicWidgets
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: GMusicWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: GMusicWidgets/GMusicWidgets.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES
        SWIFT_VERSION: "5.0"

  GMusicTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GMusicTests
    dependencies:
      - target: GMusic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivangrigin.GMusicTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
