name: GMusic
options:
  bundleIdPrefix: com.ivangrigin
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

targets:
  GMusic:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GMusic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivangrigin.GMusic
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"

  GMusicTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GMusicTests
    dependencies:
      - target: GMusic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivangrigin.GMusicTests
        SWIFT_VERSION: "5.0"
